source /usr/local/bin/virtualenvwrapper.sh

alias vim='nvim'
alias env='source ./venv/bin/activate'
alias redis='redis-server'

# show current branch
source ~/.git-prompt.sh
GIT_PS1_SHOWDIRTYSTATE=true

[ -f ~/.fzf.bash ] && source ~/.fzf.bash


export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# must go last
[[ -s "$HOME/.avn/bin/avn.sh" ]] && source "$HOME/.avn/bin/avn.sh" # load avn
