" Plugins will be downloaded under the specified directory.
call plug#begin('~/.vim/plugged')

" Declare the list of plugins.
Plug 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
Plug 'tpope/vim-sensible'
Plug 'junegunn/seoul256.vim'
Plug 'ludovicchabant/vim-gutentags'
Plug 'SirVer/ultisnips'
Plug 'ervandew/supertab'

" List ends here. Plugins become visible to Vim after this call.
call plug#end()

" nvimrc configuration
autocmd FileType python nnoremap <leader>y :0,$!yapf<Cr>
autocmd CompleteDone * pclose " To close preview window of deoplete automagically

set clipboard=unnamedplus
set mouse=a

autocmd BufRead COMMIT_EDITMSG setlocal spell spelllang=en_us textwidth=72

syntax enable
set number showmatch
let python_highlight_all = 1

" indentation config
autocmd FileType go setlocal ts=8 tw=120 autoindent
autocmd FileType python setlocal sw=4 ts=4 sts=4 tw=80 expandtab autoindent
autocmd FileType javascript setlocal sw=2 ts=2 sts=4 tw=120 expandtab autoindent
autocmd FileType yaml setlocal ts=2 sts=2 sw=2 expandtab

" spell check
set spell spelllang=en_us
